### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by JoopClaireIT** [drichardson/gogetprivate#1]
Maybe rewrite in Go?

**Comment by drichardson** [comment]
Good call, I should have written this in Go in the first place. However, I don't use this tool much so this issue is unlikely to be addressed.

**Comment by JoopClaireIT** [comment]
using this with the bash that comes with git seems to solve it anyway :)

El mar., 16 de feb. de 2016 23:42, Doug Richardson <notifications@github.com>
escribió:

> Good call, I should have written this in Go in the first place. However, I
> don't use this tool much so this issue is unlikely to be addressed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drichardson/gogetprivate/issues/1#issuecomment-184904711>
> .
>
-- 
Met vriendelijke groet,

Joop Kiefte

Claire Automotive Support - Galvanistraat 1 - 6716AE - EDE
Tel 0850020211 - www.claireit.nl

**Comment by drichardson** [comment]
Closing this as not to be fixed.
